# Generated by Django 3.2.10 on 2021-12-25 16:24

import App.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('study_goal', models.IntegerField()),
                ('Total_time', models.IntegerField()),
                ('Priority', models.PositiveSmallIntegerField()),
                ('Name', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True)),
                ('Category', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('Email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('Username', models.CharField(max_length=32, unique=True)),
                ('Firstname', models.CharField(max_length=32, null=True)),
                ('Lastname', models.CharField(max_length=32, null=True)),
                ('Password', models.CharField(max_length=32, null=True)),
                ('Coin', models.PositiveIntegerField(default=0, null=True)),
                ('Dob', models.DateField(null=True)),
                ('Chart', models.JSONField(default=App.models.User.charttime)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('Dot', models.DateField()),
                ('Tid', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Coin_amount', models.PositiveIntegerField()),
                ('Cash_amount', models.PositiveIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.user')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('Sid', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Doublecoin', models.BooleanField(default=False, null=True)),
                ('Doublecoin_time', models.DateTimeField(null=True)),
                ('Edit_username', models.BooleanField(default=False, null=True)),
                ('dark_mode', models.BooleanField(default=False)),
                ('ml', models.BooleanField(default=False)),
                ('avatar', models.CharField(max_length=32, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='App.user')),
            ],
        ),
        migrations.CreateModel(
            name='Pom',
            fields=[
                ('Pid', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('Rating', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.user'),
        ),
    ]
