# Generated by Django 3.2.8 on 2022-01-08 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_auto_20211225_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='Total_time',
            field=models.IntegerField(default=0),
        ),
    ]
