# Generated by Django 3.2.8 on 2022-01-11 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_store_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='Total_time',
            new_name='Pom_count',
        ),
    ]
