# Generated by Django 3.2.10 on 2022-01-13 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_rename_total_time_course_pom_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pom',
            name='Time',
            field=models.IntegerField(),
        ),
    ]
